
import "uikit/dist/css/uikit.min.css";   
import './globals.css'


import UIKit from  '@/components/Uikit'

export const metadata = {
  title: 'Portal Manole',
  description: 'Generated by create next app',
}

export  default function RootLayout({
  children,
}: {
  children: React.ReactNode
  }) {
  
     
  return (
    <html lang="en">
      <body> 
        
        <UIKit> {children} </UIKit>
      </body>
    </html>
  )
}
